# permissions for end users to view lendingconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: LendingConfig-viewer-role
rules:
- apiGroups:
  - clusterlendingmanager.ubie-oss.github.com
  resources:
  - lendingconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clusterlendingmanager.ubie-oss.github.com
  resources:
  - lendingconfigs/status
  verbs:
  - get
