---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - clusterlendingmanager.ubie-oss.github.com
  resources:
  - lendingconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterlendingmanager.ubie-oss.github.com
  resources:
  - lendingconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - clusterlendingmanager.ubie-oss.github.com
  resources:
  - lendingconfigs/status
  verbs:
  - get
  - patch
  - update
