name: Publish Docker image and manifests
on:
  push:
    tags:
    - 'v*'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Docker Registry
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: docker.pkg.github.com/ubie-oss/cluster-lending-manager/cluster-lending-manager-controller
    - name: Build container image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  release-manifest:
    name: Release manifest
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Set up kustomize
      uses: imranismail/setup-kustomize@2ba527d4d055ab63514ba50a99456fc35684947f # v2.1.0
    - name: kustomize build
      run: kustomize build config/crd > cluster-lending-manager-crd.yaml
    - name: Release
      uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2.0.5
      with:
        files: |
          cluster-lending-manager-crd.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
